
FROM python:3.12-slim

#Crear carpeta de trabajo en el contenedor
WORKDIR /app

#Copiar requerimientos del proyecto
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

#Copiar el proyecto
COPY ./app .

#Exponemos el Puerto
EXPOSE 5000

#comandos para ejecutar FastAPI
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000", "--reload"]